services:
  front:
    build: ./front
    container_name: chrono_front
    restart: always
  back:
    build: ./back
    container_name: chrono_back
    restart: always
  nginx:
    build: ./nginx
    container_name: chrono_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
  redis:
    image: redis
    container_name: chrono_redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password123
